
previews:
  generation: automatic # Enable preview environments

services:
  - type: web
    runtime: node
    name: cloud-bp-app
    region: frankfurt # Default: oregon
    plan: free    # Default: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bp-db
          property: connectionString


databases:
  - name: bp-db
    plan: free
    region: frankfurt
    
    
   